### ISSUE TITLE
How well does this work?

### ISSUE THREAD

**Issue by garrettwilkin** [spinscale/elasticsearch-opennlp-plugin#6]
Hello!  

This project looks like it would really suit our search needs. :+1:  How well does it work in practice? Are you satisfied with it currently?

I'm just trying to get a feel for whether or not the project is alive and well cared for.  Thanks!

:bow:

**Comment by spinscale** [comment]
I do not recommend running it in production, because I think it makes a lot more sense to have NLP running as a preprocessing step in a separated component.

First, you need to load the model into the heap of all of your elasticsearch nodes, which takes some considerable amount of memory. Second, updating the model (or even the plugin) requires a rolling cluster restart.

If you can, I propose to run this process in separation. This is one of the reasons why I havent updated the plugin in ages.
