### ISSUE TITLE
Usable?

### ISSUE THREAD

**Issue by brupm** [spinscale/elasticsearch-opennlp-plugin#9]
Hi, any reason to believe this plugin would still work? Thx.

**Comment by spinscale** [comment]
Conceptually yes, however it will not compile against current elasticsearch versions.

In addition, I also advise highly against using this, due to several reasons:

* The model can take a lot of memory (several gigabytes) of your heap, on every elasticsearch instance
* Refreshing the model requires to restart your whole cluster

All in all the plugin is doing nothing, that cannot be done as a preprocessing step. So consider putting this in your indexing pipeline which is far less resource intensive and easier to scale than putting this directly  into Elasticsearch.

Consider this a proof-of-concept, that shows, that this works but should not be considered best practice - which is also one of the reasons why I did not develop it further.

I hope this helps.
